### ISSUE TITLE
Gallery view

### ISSUE THREAD

**Issue by adamburgoyne** [CardiffBros/pub-thursday-android#37]
Add gallery view for monthly winner image.

**Comment by dylan8902** [comment]
Planning to use a Flickr Group where anyone can upload a photo but a moderator approves it. Really good rest API

https://www.flickr.com/groups/3074924@N24/

https://api.flickr.com/services/rest/?method=flickr.groups.pools.getPhotos&api_key=8597722f605f6e9890ca21f3b223da3d&group_id=3074924%40N24&format=json&nojsoncallback=1&extras=url_sq,%20url_t,%20url_s,%20url_q,%20url_m,%20url_n,%20url_z,%20url_c,%20url_l,%20url_o
